# Paths
data_folder: "../data"
scraping_folder: "scrapping"

# URLs and table configurations
tables:
  - url: "https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 0
    subdivide_columns: 37
    header_start: 8
    header_end: 45
  - url: "https://fbref.com/en/comps/Big5/2023-2024/shooting/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 1
    subdivide_columns: 26
    header_start: 5
    header_end: 31
  - url: "https://fbref.com/en/comps/Big5/2023-2024/passing/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 2
    subdivide_columns: 32
    header_start: 10
    header_end: 42
  - url: "https://fbref.com/en/comps/Big5/2023-2024/passing_types/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 3
    subdivide_columns: 24
    header_start: 6
    header_end: 30
  - url: "https://fbref.com/en/comps/Big5/2023-2024/gca/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 4
    subdivide_columns: 25
    header_start: 7
    header_end: 32
  - url: "https://fbref.com/en/comps/Big5/2023-2024/defense/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 5
    subdivide_columns: 25
    header_start: 7
    header_end: 32
  - url: "https://fbref.com/en/comps/Big5/2023-2024/possession/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 6
    subdivide_columns: 31
    header_start: 7
    header_end: 38
  - url: "https://fbref.com/en/comps/Big5/2023-2024/misc/players/2023-2024-Big-5-European-Leagues-Stats"
    table_index: 7
    subdivide_columns: 25
    header_start: 5
    header_end: 30

# Join key for DataFrames
join_key: "Player"
